### ISSUE TITLE
How to 'statically' listen for an event

### ISSUE THREAD

**Issue by micschk** [walmsles/silverstripe-event-dispatch#2]
I'm wondering if this module (events) would fit my use case; what's not really clear to me, is what would be a SilverStripe-esque way for many objects to be subscribed/listening to a certain event. I think some frameworks allow facilitate this by a config setting for a mapping between events and methods to be called. But in Silverstripe I'm not aware of a mechanism for this kind of pattern.

E.g. I have 5000 dataobjects, of which some would need to run some action based on a specific event. Now would I need to instantiate all 5000 objects, have them subscribe to events, and then dispatch the actual event? (This would limit scalability, and I could actually just call a general update method directly on all of them?)

Or is my understanding of events/observer-pattern incorrect?
I'm starting to think perhaps I'm looking at this too much from a Javascript perspective, maybe in PHP the observer-pattern is more about loose coupling/flexibility then about subscribing/notification/updating?

**Comment by micschk** [comment]
E.g. $listen config in Laravel: https://laravel.com/docs/5.4/events#registering-events-and-listeners

**Comment by walmsles** [comment]
Hi micshk, this package is very much modelled on the Laravel event subscribe/listen pattern.  It's more of loose  coupling of processing or callbacks than a fully fledged notification system for object attribute updates.

I would be wary of trying to load 5000 data objects with a silverstripe data list and then trying to process it.  This would be very non-scalable and certainly you would need to be wary of daemons under the hood. 

I would certainly recommend bulk update actions - if one event affects so many objects I would be using specific events for specific updates which could then bulk update other records matching your required criteria.

This was a simple project which I introduced for a private  e-commerce style module needed to out together in order to isolate sand decouple processing code for order placement routines, stock management and email notifications.

Not sure I have helped but wish you well in finding your solution.

**Comment by micschk** [comment]
Thanks, this has helped indeed. Combined with some more reading I got a better grasp of the observer-pattern. 

I'm using your module for a simplified workflows module. Specifically to keep the logic/knowledge for processing workflow-status updates on the dataobject (instead of on the workflow-status having to know how to publish an object). Workflow-statusses simply emit a 'you were updated to status XY' event which the object itself knows how to handle (eg Publish itself and run some optional actions).

Will let you know when I may get around to publishing it.
